config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users, controllers: {
    sessions:      'admin_users/sessions',
    passwords:     'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  resources :posts
  resources :comments, only: [ :create, :destroy ]
  resources :users, only: :show

  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def like
    like = Like.new(post_id: params[:post_id], user_id: current_user.id)
    like.save
  end

  def unlike
    like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    like.destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<div id="like-link-<%= post.id %>">
  <% if current_user.likes.find_by(post_id: post.id) %>
    <%= link_to "♥", unlike_path(post), method: :delete, class: "like", remote: true %>
  <% else %>
    <%= link_to "♡", like_path(post), method: :post, class: "unlike", remote: true %>
  <% end %>
  <%= post.likes_count %>
</div>

app/views/likes/like.js.erb
$("<%= "#like-link-#{@post.id}" %>").html('<%= escape_javascript(render("likes/like", post: @post )) %>');

app/views/likes/unlike.js.erb
$("<%= "#like-link-#{@post.id}" %>").html('<%= escape_javascript(render("likes/like", post: @post )) %>');